services:
  mysql_shipping:
    image: mysql:8.0
    container_name: mysql_shipping
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_ab_test
      MYSQL_USER: devcharlie
      MYSQL_PASSWORD: devcharlie
    ports:
      - "3308:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password